---
apiVersion: garden.sapcloud.io/v1beta1
kind: CloudProfile
metadata:
  name: metal
spec:
# caBundle: |
#   -----BEGIN CERTIFICATE-----
#   ...
#   -----END CERTIFICATE-----
  metal:
    constraints:
      dnsProviders:
      - name: route53
      - name: unmanaged
      kubernetes:
        versions:
        - 1.14.3
      loadBalancerProviders:
      - name: metallb
      machineImages:
      - name: metal
        image: ubuntu-19.04
      machineTypes:
      - name: c1-xlarge-x86
        cpu: "1"
        gpu: "0"
        memory: 1Gi
        usable: true
        volumeType: default
        volumeSize: 20Gi
      zones:
      - region: nbg
        names:
        - nbg-w8101
