# Secret containing cloud provider credentials for Metal tenant into which the Seed cluster have been provisioned.
---
apiVersion: v1
kind: Secret
metadata:
  name: seed-metal
  namespace: garden
type: Opaque
data:
  kubeconfig: base64(kubeconfig-for-seed-cluster)
  tenant: base64(tenant)
  metalAPIURL: base64(metal-api-url)
  metalAPIKey: base64(metal-api-key)
  metalAPIHMac: base64(metal-api-hmac)
