---
apiVersion: garden.sapcloud.io/v1beta1
kind: Shoot
metadata:
  name: johndoe-metal
  namespace: garden-dev
spec:
  cloud:
    profile: metal
    region: nbg
    secretBindingRef:
      name: core-metal
    metal:
      loadBalancerProvider: metallb
      networks: 
        nodes: "192.168.1.0/24"
      workers:
      - name: cpu-worker
        machineType: c1-xlarge-x86
        autoScalerMin: 2
        autoScalerMax: 2
        maxSurge: 1
        maxUnavailable: 0
      machineImage: 
        name: "metal"
        image: "ubuntu-19.04"
      zones: ['nbg-w8101']
  kubernetes:
    version: 1.14.0
    allowPrivilegedContainers: true # 'true' means that all authenticated users can use the "gardener.privileged" PodSecurityPolicy, allowing full unrestricted access to Pod features.
  # kubeAPIServer:
  #   featureGates:
  #     SomeKubernetesFeature: true
  #   runtimeConfig:
  #     scheduling.k8s.io/v1alpha1: true
  #   oidcConfig:
  #     caBundle: |
  #       -----BEGIN CERTIFICATE-----
  #       Li4u
  #       -----END CERTIFICATE-----
  #     clientID: client-id
  #     groupsClaim: groups-claim
  #     groupsPrefix: groups-prefix
  #     issuerURL: https://identity.example.com
  #     usernameClaim: username-claim
  #     usernamePrefix: username-prefix
  #     signingAlgs: RS256,some-other-algorithm
  #-#-# only usable with Kubernetes >= 1.11
  #     requiredClaims:
  #       key: value
  #   admissionPlugins:
  #   - name: PodNodeSelector
  #     config: |
  #       podNodeSelectorPluginConfig:
  #         clusterDefaultNodeSelector: <node-selectors-labels>
  #         namespace1: <node-selectors-labels>
  #         namespace2: <node-selectors-labels>
  #   auditConfig:
  #     auditPolicy:
  #       configMapRef:
  #         name: auditpolicy
  # cloudControllerManager:
  #   featureGates:
  #     SomeKubernetesFeature: true
  # kubeControllerManager:
  #   featureGates:
  #     SomeKubernetesFeature: true
  #   horizontalPodAutoscaler:
  #     syncPeriod: 30s
  #     tolerance: 0.1
  #-#-# only usable with Kubernetes < 1.12
  #     downscaleDelay: 15m0s
  #     upscaleDelay: 1m0s
  #-#-# only usable with Kubernetes >= 1.12
  #     downscaleStabilization: 5m0s
  #     initialReadinessDelay: 30s
  #     cpuInitializationPeriod: 5m0s
  # kubeScheduler:
  #   featureGates:
  #     SomeKubernetesFeature: true
  # kubeProxy:
  #   featureGates:
  #     SomeKubernetesFeature: true
  # kubelet:
  #   featureGates:
  #     SomeKubernetesFeature: true
  dns:
    provider: unmanaged
    domain: johndoe-metal.garden-dev.example.com
# hibernation:
#   enabled: false
#   schedules:
#   - start: "0 20 * * *" # Start hibernation every day at 8PM
#     end: "0 6 * * *"    # Stop hibernation every day at 6AM
  maintenance:
    timeWindow:
      begin: 220000+0100
      end: 230000+0100
    autoUpdate:
      kubernetesVersion: true
  # Backup configuration for Shoot clusters is deprecated and no longer supported.
  # The responsibility for these settings has been shifted to Garden administrators.
  # This field will be removed in the future and is only kept for API compatibility reasons. It is not
  # evaluated or respected at all. Please do not use this field anymore.
  backup:
    schedule: "0 */24 * * *"
    maximum: 7
  addons:
    kubernetes-dashboard:
      enabled: true