required = [
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/conversion-gen",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "k8s.io/kube-openapi/cmd/openapi-gen",

  "github.com/gardener/gardener-extensions/controllers/provider-aws/pkg/apis/aws/v1alpha1",
  "github.com/gardener/gardener-extensions/controllers/provider-azure/pkg/apis/azure/v1alpha1",
  "github.com/gardener/gardener-extensions/controllers/provider-gcp/pkg/apis/gcp/v1alpha1",
  "github.com/gardener/gardener-extensions/controllers/provider-openstack/pkg/apis/openstack/v1alpha1",
  "github.com/gardener/gardener-extensions/controllers/provider-alicloud/pkg/apis/alicloud/v1alpha1",
  "github.com/gardener/gardener-extensions/controllers/provider-packet/pkg/apis/packet/v1alpha1"
]

ignored = [
  "github.com/spf13/afero/sftp"
]

# Only temporarily needed for migration purposes
[[constraint]]
  name = "github.com/gardener/gardener-extensions"
  revision = "f09dd7bc8d2fee9f4cfff1d95d39e7713728bf81"

# Only temporarily needed for migration purposes
[[constraint]]
  name = "github.com/metal-pod/gardener-extension-provider-metal"
  revision = "cd5356483498255a4c2607db01cf8d5298a75a71"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.14.0"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.14.0"

[[override]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.14.0"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.14.0"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.14.0"

[[override]]
  name = "k8s.io/cluster-bootstrap"
  version = "kubernetes-1.14.0"

[[override]]
  name = "k8s.io/component-base"
  version = "kubernetes-1.14.0"

[[override]]
  name = "k8s.io/kube-aggregator"
  version = "kubernetes-1.14.0"

[[override]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.14.0"

[[override]]
  name = "k8s.io/kube-openapi"
  revision = "5e45bb682580c9be5ffa4d27d367f0eeba125c7b" # kubernetes-1.14.0

[[override]]
  name = "k8s.io/klog"
  version = "v0.1.0"

[[override]]
  name = "sigs.k8s.io/controller-runtime"
  version = "v0.2.0-beta.2"

[[override]]
  name = "github.com/jmespath/go-jmespath"
  revision = "c2b33e84"

[[override]]
  name = "github.com/coreos/etcd"
  version = "3.3.10"

[[constraint]]
  name = "github.com/aliyun/aliyun-oss-go-sdk"
  version = "1.9.5"

[[override]]
  name = "github.com/gardener/external-dns-management"
  version = "0.1.0"

[[constraint]]
  name = "github.com/gardener/machine-controller-manager"
  revision = "e95a18defae11c83c638d2a834c5ed0b76ed87d6"
  source = "github.com/majst01/machine-controller-manager"

[[constraint]]
  name = "k8s.io/helm"
  version = "v2.7.2"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.9.0"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "~1.12.48"

[[constraint]]
  name = "github.com/ghodss/yaml"
  version = "^1.0.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "^0.0.1"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "^1.0.4"

[[constraint]]
  name = "github.com/Masterminds/semver"
  version = "~1.4.0"

[[constraint]]
  name = "github.com/robfig/cron"
  revision = "2315d5715e36303a941d907f038da7f7c44c773b"

# use the same version that is referenced by k8s.io/apiserver
[[override]]
  name = "github.com/evanphx/json-patch"
  revision = "5858425f75500d40c52783dce87d085a483ce135"

[[override]]
  name = "sigs.k8s.io/structured-merge-diff"
  revision = "e85c7b244fd2cc57bb829d73a061f93a441e63ce"

[[constraint]]
  name = "github.com/hashicorp/go-multierror"
  revision = "3d5d8f294aa03d8e98859feac328afbdf1ae0703"

[[constraint]]
  name = "github.com/pkg/errors"
  revision = "816c9085562cd7ee03e7f8188a1cfd942858cded"

# Dependencies for testing purposes only
[[constraint]]
  name = "github.com/onsi/gomega"
  version = "~1.3.0"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "~1.4.0"

[[constraint]]
  name = "github.com/golang/mock"
  version = "1.2.0"

[[constraint]]
  name = "golang.org/x/crypto"
  revision = "a5d413f7728c81fb97d96a2b722368945f651e78"

[[constraint]]
  branch = "master"
  name = "github.com/metal-pod/metal-go"

[[override]]
  name = "github.com/go-openapi/analysis"
  version = "0.19.0"
[[override]]
  name = "github.com/go-openapi/errors"
  version = "0.19.0"
[[override]]
  name = "github.com/go-openapi/jsonpointer"
  version = "0.19.0"
[[override]]
  name = "github.com/go-openapi/jsonreference"
  version = "0.19.0"
[[override]]
  name = "github.com/go-openapi/loads"
  version = "0.19.0"
[[override]]
  name = "github.com/go-openapi/runtime"
  version = "0.19.0"
[[override]]
  name = "github.com/go-openapi/spec"
  version = "0.19.0"
[[override]]
  name = "github.com/go-openapi/strfmt"
  version = "0.19.0"
[[override]]
  name = "github.com/go-openapi/swag"
  version = "0.19.0"
[[override]]
  name = "github.com/go-openapi/validate"
  version = "0.19.0"
  
  
# use the same version that is referenced by k8s.io, mainly required by Helm
# https://github.com/kubernetes/kubernetes/blob/v1.13.1/Godeps/Godeps.json#L2996
[[override]]
  name = "github.com/russross/blackfriday"
  revision = "300106c228d52c8941d4b3de6054a6062a86dda3"

[prune]
  unused-packages = true
  go-tests = true
  non-go = true

  [[prune.project]]
    name = "k8s.io/code-generator"
    unused-packages = false
    non-go = false

  [[prune.project]]
    name = "k8s.io/kube-openapi"
    unused-packages = false
    non-go = false
