apiVersion: v1
kind: Namespace
metadata:
  name: kube-system
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    app: metallb
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: kube-system
  name: controller
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    app: metallb
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: kube-system
  name: speaker
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    app: metallb
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-system:controller
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    app: metallb
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: [""]
    resources: ["services/status"]
    verbs: ["update"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-system:speaker
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    app: metallb
rules:
  - apiGroups: [""]
    resources: ["services", "endpoints", "nodes"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: kube-system
  name: config-watcher
  labels:
    app: metallb
    addonmanager.kubernetes.io/mode: Reconcile
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create"]
---

## Role bindings
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-system:controller
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    app: metallb
subjects:
  - kind: ServiceAccount
    name: controller
    namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-system:controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-system:speaker
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    app: metallb
subjects:
  - kind: ServiceAccount
    name: speaker
    namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-system:speaker
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: kube-system
  name: config-watcher
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    app: metallb
subjects:
  - kind: ServiceAccount
    name: controller
  - kind: ServiceAccount
    name: speaker
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: config-watcher
