# List of all container images which are deployed by the Gardener.
# In case an image can only be used for a specific Kubernetes version, the
# entry must have a key "runtimeVersion" whose value describe for which kubernetes runtime
# the respective tag can be used. The syntax must be as described in the
# Masterminds/semver package: https://github.com/Masterminds/semver#hyphen-range-comparisons.
images:
# Seed bootstrap
- name: pause-container
  sourceRepository: github.com/kubernetes/kubernetes/blob/master/build/pause/Dockerfile
  repository: gcr.io/google_containers/pause-amd64
  tag: "3.1"

# Seed controlplane
- name: etcd
  sourceRepository: github.com/coreos/etcd
  repository: quay.io/coreos/etcd
  tag: v3.3.13
- name: etcd-backup-restore
  sourceRepository: github.com/gardener/etcd-backup-restore
  repository: eu.gcr.io/gardener-project/gardener/etcdbrctl
  tag: "0.6.4"
- name: hyperkube
  sourceRepository: github.com/kubernetes/kubernetes
  repository: k8s.gcr.io/hyperkube
- name: machine-controller-manager
  sourceRepository: github.com/gardener/machine-controller-manager
  repository: eu.gcr.io/gardener-project/gardener/machine-controller-manager
  tag: "0.19.0-dev" # only for metal-dev!
- name: cluster-autoscaler
  sourceRepository: github.com/gardener/autoscaler
  repository: eu.gcr.io/gardener-project/gardener/autoscaler/cluster-autoscaler
  tag: "0.4.0"
- name: kube-addon-manager
  sourceRepository: github.com/kubernetes/kubernetes/tree/master/cluster/addons/addon-manager
  repository: k8s.gcr.io/kube-addon-manager
  tag: v9.0
- name: vpn-seed
  sourceRepository: github.com/gardener/vpn
  repository: eu.gcr.io/gardener-project/gardener/vpn-seed
  tag: "0.14.0"
- name: aws-lb-readvertiser
  sourceRepository: github.com/gardener/aws-lb-readvertiser
  repository: eu.gcr.io/gardener-project/gardener/aws-lb-readvertiser
  tag: "0.6.0"
- name: dependency-watchdog
  sourceRepository: github.com/gardener/dependency-watchdog
  repository: eu.gcr.io/gardener-project/gardener/dependency-watchdog
  tag: "0.1.1"

# Monitoring
- name: alertmanager
  sourceRepository: github.com/prometheus/alertmanager
  repository: quay.io/prometheus/alertmanager
  tag: v0.15.3
- name: prometheus
  sourceRepository: github.com/prometheus/prometheus
  repository: quay.io/prometheus/prometheus
  tag: v2.7.1
- name: configmap-reloader
  sourceRepository: github.com/jimmidyson/configmap-reload
  repository: quay.io/coreos/configmap-reload
  tag: v0.0.1
- name: kube-state-metrics
  sourceRepository: github.com/kubernetes/kube-state-metrics
  repository: quay.io/coreos/kube-state-metrics
  tag: v1.4.0
- name: node-exporter
  sourceRepository: github.com/prometheus/node_exporter
  repository: quay.io/prometheus/node-exporter
  tag: v0.17.0
- name: grafana
  sourceRepository: github.com/grafana/grafana
  repository: grafana/grafana
  tag: "6.1.4"
- name: blackbox-exporter
  sourceRepository: github.com/prometheus/blackbox_exporter
  repository: quay.io/prometheus/blackbox-exporter
  tag: v0.13.0
- name: metrics-server
  sourceRepository: github.com/kubernetes-incubator/metrics-server
  repository: k8s.gcr.io/metrics-server-amd64
  tag: v0.3.1

# Shoot core addons
- name: metallb-speaker
  sourceRepository: github.com/danderson/metallb
  repository: metallb/speaker
  tag: v0.7.3
- name:  metallb-controller
  sourceRepository: github.com/danderson/metallb
  repository: metallb/controller
  tag: v0.7.3
- name: calico-node
  sourceRepository: github.com/projectcalico/calico
  repository: quay.io/calico/node
  tag: v3.7.2
- name: calico-cni
  sourceRepository: github.com/projectcalico/cni-plugin
  repository: quay.io/calico/cni
  tag: v3.7.2
- name: calico-typha
  sourceRepository: github.com/projectcalico/typha
  repository: quay.io/calico/typha
  tag: v3.7.2
- name: calico-kube-controllers
  sourceRepository: github.com/projectcalico/typha
  repository: quay.io/calico/kube-controllers
  tag: v3.7.2
- name: vpn-shoot
  sourceRepository: github.com/gardener/vpn
  repository: eu.gcr.io/gardener-project/gardener/vpn-shoot
  tag: "0.14.0"
- name: coredns
  sourceRepository: github.com/coredns/coredns
  repository: coredns/coredns
  tag: "1.4.0"

# Alicloud Controller Manger
- name: alicloud-controller-manager
  sourceRepository: https://github.com/kubernetes/cloud-provider-alibaba-cloud
  repository: registry.eu-central-1.aliyuncs.com/gardener-de/alibaba-cloud-controller-manager
  tag: "1.9.8"

# Packet Controller Manager
- name: packet-controller-manager
  sourceRepository: https://github.com/packethost/packet-ccm
  repository: docker.io/packethost/packet-ccm
  tag: "master"

# Packet Storage Interface
- name: packet-storage-interface
  sourceRepository: https://github.com/packethost/csi-packet
  repository: docker.io/packethost/csi-packet
  tag: "73641b0"

# Shoot optional addons
- name: kubernetes-dashboard
  sourceRepository: github.com/kubernetes/dashboard
  repository: k8s.gcr.io/kubernetes-dashboard-amd64
  tag: v1.10.1
- name: kube-lego
  sourceRepository: github.com/jetstack/kube-lego
  repository: jetstack/kube-lego
  tag: "0.1.7"
- name: kube2iam
  sourceRepository: github.com/jtblin/kube2iam
  repository: jtblin/kube2iam
  tag: "0.10.4"
- name: nginx-ingress-controller
  sourceRepository: github.com/kubernetes/ingress-nginx
  repository: quay.io/kubernetes-ingress-controller/nginx-ingress-controller
  tag: "0.22.0"
- name: ingress-default-backend
  sourceRepository: github.com/gardener/ingress-default-backend
  repository: eu.gcr.io/gardener-project/gardener/ingress-default-backend
  tag: "0.7.0"

# Miscellaenous
- name: terraformer
  sourceRepository: github.com/gardener/terraformer
  repository: eu.gcr.io/gardener-project/gardener/terraformer
  tag: "0.13.0"
- name: busybox
  sourceRepository: github.com/mirror/busybox
  repository: busybox
  tag: "1.29.2"
- name: alpine
  repository: alpine
  tag: "3.8"
- name: alpine-iptables
  repository: eu.gcr.io/gardener-project/alpine-iptables
  tag: "3.9"

# CSI
- name: csi-attacher
  sourceRepository: https://github.com/kubernetes-csi/external-attacher
  repository: quay.io/k8scsi/csi-attacher
  tag: v1.0.1
  runtimeVersion: 1.13.x
- name: csi-attacher
  sourceRepository: https://github.com/kubernetes-csi/external-attacher
  repository: quay.io/k8scsi/csi-attacher
  tag: v1.1.0
  runtimeVersion: 1.14.x
- name: csi-node-driver-registrar
  sourceRepository: https://github.com/kubernetes-csi/node-driver-registrar
  repository: quay.io/k8scsi/csi-node-driver-registrar
  tag: v1.0.1
  runtimeVersion: 1.13.x
- name: csi-node-driver-registrar
  sourceRepository: https://github.com/kubernetes-csi/node-driver-registrar
  repository: quay.io/k8scsi/csi-node-driver-registrar
  tag: v1.1.0
  runtimeVersion: 1.14.x
- name: csi-provisioner
  sourceRepository: https://github.com/kubernetes-csi/external-provisioner
  repository: quay.io/k8scsi/csi-provisioner
  tag: v1.0.1
  runtimeVersion: 1.13.x
- name: csi-provisioner
  sourceRepository: https://github.com/kubernetes-csi/external-provisioner
  repository: quay.io/k8scsi/csi-provisioner
  tag: v1.1.0
  runtimeVersion: 1.14.x
- name: csi-snapshotter
  sourceRepository: https://github.com/kubernetes-csi/external-snapshotter
  repository: quay.io/k8scsi/csi-snapshotter
  tag: v1.0.1
  runtimeVersion: 1.13.x
- name: csi-snapshotter
  sourceRepository: https://github.com/kubernetes-csi/external-snapshotter
  repository: quay.io/k8scsi/csi-snapshotter
  tag: v1.1.0
  runtimeVersion: 1.14.x
- name: csi-plugin-alicloud
  sourceRepository: https://github.com/AliyunContainerService/csi-plugin
  repository: registry.eu-central-1.aliyuncs.com/gardener-de/csi-plugin-alicloud
  tag: v1.13.2

# Logging
- name: fluentd-es
  sourceRepository: github.com/gardener/logging
  repository: eu.gcr.io/gardener-project/gardener/fluentd-es
  tag: "0.19.0"
- name: fluent-bit
  sourceRepository: github.com/fluent/fluent-bit
  repository: fluent/fluent-bit
  tag: "1.0.6"
- name: elasticsearch-oss
  sourceRepository: github.com/elastic/elasticsearch-docker
  repository: docker.elastic.co/elasticsearch/elasticsearch-oss
  tag: "6.7.1"
- name: elasticsearch-metrics-exporter
  sourceRepository: github.com/justwatchcom/elasticsearch_exporter
  repository: justwatch/elasticsearch_exporter
  tag: "1.0.2"
- name: elasticsearch-searchguard-oss
  sourceRepository: github.com/floragunncom/search-guard
  repository: floragunncom/sg-elasticsearch
  tag: "6.7.1-oss-25.0"
- name: curator-es
  sourceRepository: github.com/gardener/logging
  repository: eu.gcr.io/gardener-project/gardener/curator-es
  tag: "0.19.0"
- name: kibana-oss
  sourceRepository: github.com/elastic/kibana-docker
  repository: docker.elastic.co/kibana/kibana-oss
  tag: "6.7.1"
- name: sg-sgadmin
  sourceRepository: github.com/floragunncom/search-guard
  repository: floragunncom/sg-sgadmin
  tag: "6.7.1-25.0"

# VPA
- name: vpa-admission-controller
  sourceRepository: github.com/kubernetes/autoscaler
  repository: k8s.gcr.io/vpa-admission-controller
  tag: "0.5.0"
- name: vpa-recommender
  sourceRepository: github.com/kubernetes/autoscaler
  repository: k8s.gcr.io/vpa-recommender
  tag: "0.5.0"
- name: vpa-updater
  sourceRepository: github.com/kubernetes/autoscaler
  repository: k8s.gcr.io/vpa-updater
  tag: "0.5.0"
- name: vpa-exporter
  sourceRepository: github.com/gardener/vpa-exporter
  repository: eu.gcr.io/gardener-project/gardener/vpa-exporter
  tag: "0.1.5"
