apiVersion: {{ include "storageclassversion" . }}
kind: StorageClass
metadata:
  name: {{ $.Values.name }}
provisioner: {{ $.Values.provisioner }}
allowVolumeExpansion: true
parameters:
{{- if $.Values.parameters }}
{{ toYaml $.Values.parameters | indent 2 }}
{{- end }}
{{- if $.Values.volumeBindingMode }}
volumeBindingMode: {{ $.Values.volumeBindingMode }}
{{- end }}
