apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: metallb-config
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
data:
  config: |
    address-pools:
    {{- range $name, $ips := .Values.config }}
    - name: "{{ $name }}"
      protocol: layer2
      addresses:
      {{- range $index, $ip := $ips }}
      - "{{ $ip }}"
      {{- end }}
    {{- end }}
